# Generated by Django 6.0.1 on 2026-02-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_leaverecord_student_alter_complaint_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_complaints',
        ),
    ]
